### ISSUE TITLE
Xcode project doesn't include LSData.swift

### ISSUE THREAD

**Issue by SuperWomble** [loosestar/MissTableViewNavigationController#1]
This is a strange one. I forked the project, and opened it in Xcode. Immediately got build errors, saying that LSData was unknown.

Yet the forked package included LSData.swift. To fix this I had to manually add LSData.swift to file the Xcode project. It then built.

Maybe check that the Target property for LSData.swift is set correctly?

**Comment by loosestar** [comment]
I've had a look at it, the target membership is fine, and the file is in the package you grabbed (as you noticed).

Hard to decipher seeing as it all seemed superficially correct. I pulled the project and noticed the same problem, so I did the naive thing (which worked) by doing what you did (praise be all powerful TimeMachine for bringing the file back after pulling the project deleted it ;) ), then committing and pushing. Strange.

**Comment by SuperWomble** [comment]
Re-grabbed, working now. Good stuff.
