### ISSUE TITLE
Suggestion: model data should be read-only, abstracted

### ISSUE THREAD

**Issue by SuperWomble** [loosestar/MissTableViewNavigationController#2]
Currently, LSData is a class, and includes two 'var' properties. Once of these is a force unwrapped Optional.

1.  Generally, most model data in Swift should be in Structs, and preferably members of the struct should be read-only. (i.e. 'let')

e.g. 

```
struct LS_NameModel
{
    let id: Int
    let name: String
}
```

Instead of modifying a value type, you instead create a new value type. This is a core principle of functional programming.

**The use of 'var' should be quite rare throughout a project.**

e.g. 

```
let name = "Liam"
let uppercasedName = name.uppercased()
```

Here, the value type "Liam" has been used to create a new value type "LIAM". Instead of modifying the value "Liam", we instead create a new value altogether.

Value types  help remove mutability (and thus surprises) from your code. Any time you can make things non-mutable, you should. It's a core principle of Swift. And Value-types remove entire classes of bugs and design mistakes.

Swift has been designed to make passing around Value types (e.g. Arrays of structs) very efficient. (The compiler is clever enough to know that it doesn't really need to copy things.) 

The use of Reference types (e.g. classes) should be rare. Unfortunately, CocoaTouch is full of them (UIViewController, UIButton etc.)  If Cocoa were rewritten today, much of it would be based around Structs, Protocols and composition rather than subclasses.

2. Avoid the use of optionals and force-unwrapped optionals in models if you can. Optionals introduce mutability (and thus uncertainty). There absolutely are uses for Optionals, but err on the side of not using them.

**Suggestion**: replace LSData with a struct containing read-only properties.

**Comment by loosestar** [comment]
LSData is now a struct, LS_Data with an extension of its description

**Comment by loosestar** [comment]
Wondering about viability of default data as opposed to undefined variables...

**Comment by SuperWomble** [comment]
What do you mean?

**Comment by loosestar** [comment]
For id, for instance, -1 or some other magic number, and an empty string for name?

**Comment by SuperWomble** [comment]
I don't understand what you mean.

If you want a proper ID you could use `UUID`. (Get used to using this in SwiftUI, BTW!)

If you want to provide defaults, you can do so through the init method.

e.g.

```
struct LS_NameModel
{
    let id: UUID
    let name: String

    init(id: UUID = UUID(), name: String) {
        self.id = id
        self.name = name
    }
}

```
For empty strings, you would just use an empty, non-optional string.

Again, err on the side of not using Optionals in data models. If there is no name for some reason, an empty string will suffice.

OTOH, if you want to indicate that there is no NameModel at all, then you would make the entire model an optional.
e..g 

var nameModel: LS_NameModel?

For reasons of understanding, I typically call these "maybe" variables. As in, they may have a value, or many not. And I describe them as such:

```
var maybeNameModel: LSNameModel?

...

if let nameModel = self.maybeNameModel {
    print(nameModel.name)
}

```

**Comment by SuperWomble** [comment]
BTW, if you ever see a -1 in your code, you've done something wrong. :)  Use an Optional for that, or an Enum.

**Comment by loosestar** [comment]
Old habits! :( Also, thanks for showing/reminding me I can init() inside a struct declaration. This changes everything.

**Comment by SuperWomble** [comment]
"If Cocoa were rewritten today, much of it would be based around Structs, Protocols and composition rather than subclasses."

And bang, there we have it. SwiftUI. 

The WWDC videos on SwiftUI are eye-opening. Have to change a lot of thinking and habits!

**Comment by loosestar** [comment]
Pretty!
![image](https://user-images.githubusercontent.com/302438/59082282-ac63bb80-8935-11e9-9c47-ad3ef0e45d4e.png)

Will check out the WWDC vids later, or do you think it's worth doing now so I'm on the right page rather than merrily developing away in soon to be obsolete libraries?

**Comment by loosestar** [comment]
Yikes, lost track of this one. Updated the model to be a read-only struct.
