### ISSUE TITLE
Replicating class properties

### ISSUE THREAD

**Issue by SuperWomble** [loosestar/MissTableViewNavigationController#3]
In ExampleTableViewController, there is:

```
 private var egTableView: UITableView!
private var egNavBar: UINavigationBar!
```

These are not needed.

A tableViewController instance already has a 'tableView' property. The UITableViewController already provides it: that's its job.

A tableViewController can be contained/embedded/wrapped in a UINavigationController (but doesn't have to be). So it has an Optional 'navigationController' property you can access. (This is actually a poor design, but there you go.)

The navigationBar is provided by any UINavigationController. You don't make it, or store a reference to it.

**Suggestion**: remove all custom tableView and navigationBar vars.

**Comment by loosestar** [comment]
Ta. I think I half realised this which is why quite a few of their respective uses were commented out, but nervous as always to actually pull the plug. Gone now, still functioning.
