### ISSUE TITLE
Editing - Add button should be disabled

### ISSUE THREAD

**Issue by SuperWomble** [loosestar/MissTableViewNavigationController#4]
After tapping the "Edit" button, and thus entering Edit mode, the Add (+) button is still available. This leads to confusion and bugs during editing.

**Suggestion**: disable (or remove) the Add button when entering Edit mode, and restore it when Edit mode has ended.

Whether to remove the button or disable it comes down to aesthetic and user expectations. Technically, you want to disable it. But sometimes, it's simply preferable to reduce the visual clutter and make it absolutely clear that the only thing you can do in Edit mode is edit.

(It's like entering an "Edit" mode when editing a photo: you expect everything else ("New album", "Share" etc.) to disappear, leaving you only with photo editing controls.)

**Comment by loosestar** [comment]
Ta, boolean assignment on leftBarButtonItem?.isEnabled in setEditing() does the job. A...little obfuscated
