### ISSUE TITLE
Naming of IBActions, functions

### ISSUE THREAD

**Issue by SuperWomble** [loosestar/MissTableViewNavigationController#6]
In ExampleTableViewController.swift, there is this IBAction method:

`@objc func myNewButtonItem(sender: UIBarButtonItem) { ... }`

The noun 'myNewButtonitem' suggests that this is a property or value type, rather than a function.

**Suggestion**: use verbs and/or language that suggest the result or purpose of the type.

e.g. 

` func handleAddButtonTapped(...)`

or, very commonly used with closures:

` func onAddButtonTapped(...)`

**Comment by loosestar** [comment]
Makes the code easier to read, too.
