### ISSUE TITLE
LSData description property

### ISSUE THREAD

**Issue by SuperWomble** [loosestar/MissTableViewNavigationController#7]
It's recommended that the `description` property isn't read directly. Instead, `String(describing:)` is used.

And the type should conform to `CustomStringConvertible`, which dictates the use of 'description'.

See:

https://developer.apple.com/documentation/swift/customstringconvertible

i.e.

```
extension LS_Data: CustomStringConvertible
{
    var description: String {
        return "id: \(id)" + "name: \(name)"
    }
}
```

**Comment by loosestar** [comment]
Good call. Safer, neater.
